services:
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: unless-stopped
    environment:
    - AUTOHEAL_CONTAINER_LABEL=all
    - AUTOHEAL_INTERVAL=30
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - AUTOHEAL_START_PERIOD=0
    - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    - DOCKER_SOCK=/var/run/docker.sock
    - CURL_TIMEOUT=30
    - WEBHOOK_URL=
    - WEBHOOK_JSON_KEY=content
    - APPRISE_URL=
    - POST_RESTART_SCRIPT=
    command:
    - autoheal
    entrypoint:
    - /docker-entrypoint
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
