services:
  vaultwarden:
    image: vaultwarden/server@sha256:094b5689ed81549bd293418395c7cf495ae9d960fc2d4928cef2083ef913d912
    container_name: vaultwarden
    environment:
      ROCKET_PROFILE: release
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 80
    volumes:
      - /opt/stacks/vaultwarden/data:/data
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true
