services:
  redis:
    image: redis@sha256:71da9275c5f3fcb97d0fa0c8c5b36cc995327265420f17a04bfd544f458059f7
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: postgres@sha256:9b1d34adbce1dd07ee6e94b4a2cf698884b89bd44a6c9c12f5da8f3acbfe4957
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paperless -d paperless || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx@sha256:5ab4f4f9bb099a36bec3e092906ea3e611323c5f18dc5cc38c76a1d540bdca9c
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "8010:8000"
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_TIME_ZONE: Europe/London
      PAPERLESS_SECRET_KEY: "${PAPERLESS_SECRET_KEY}"
      PAPERLESS_CONSUMER_POLLING: 10
    volumes:
      - ./data/data:/usr/src/paperless/data
      - /mnt/synology/Joshan/paperless_media:/usr/src/paperless/media
      - /mnt/synology/Joshan/paperless_export:/usr/src/paperless/export
      - /mnt/synology/Joshan/Intake:/usr/src/paperless/consume
    networks:
      - default
      - reverse_proxy

volumes:
  redis_data:
    external: true
    name: paperless_redis_data

networks:
  reverse_proxy:
    external: true
