version: "3.9"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8090
    volumes:
      - /opt/stacks/qbittorrent/config:/config
      - /mnt/synology/LifeOS/Downloads:/downloads
    ports:
      - "8090:8090"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true
