services:
  zwave-js-ui:
    image: zwavejs/zwave-js-ui:latest
    container_name: zwave-js-ui
    environment:
      NODE_ENV: production
      TAG_NAME: ""
    devices:
      - /dev/ttyACM0:/dev/zwave
    volumes:
      - /opt/stacks/zwave/store:/usr/src/app/store
    ports:
      - "8091:8091"
      - "3100:3000"
    restart: unless-stopped
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true
